name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Install Dependencies
        run: flutter pub get

      # - name: Analyze Code
      #   run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run Tests
        run: flutter test

      - name: Build APK (Android)
        run: flutter build apk --debug

      - name: Build Web
        run: flutter build web

      - name: Upload APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload Web Build
        uses: actions/upload-artifact@v4.6.2
        with:
          name: web-build
          path: build/web